### ISSUE TITLE
fetch with credentials included does not send cookies

### ISSUE THREAD

**Issue by bdefore** [kzahel/connection-forwarder#1]
I'm using fetch with `credentials: 'include'` and have cookies set for my localhost:8080 domain but do not see them being applied to the request headers. Running my node server in a crostini VM works otherwise. On an i5 Pixelbook with Chrome dev channel v68.

**Comment by kzahel** [comment]
This app is not HTTP-aware. It simply works at the TCP level.

However I could see there being problems with the Host: header. Maybe try changing localhost to 127.0.0.1 and see if there's any difference?

My thought is that the node.js backend is calling set-cookie with domain `{VM_IP}` and you'd need to let the node.js backend to use localhost or 127.0.0.1

**Comment by bdefore** [comment]
Either the update to 69 dev channel of ChromeOS or an unrelated update to our webserver appears to have fixed my symptoms. Closing.
